function [ ] = gen_merged_fmtMatrices_attentionComp(dataPaths)
%GEN_MERGED_FMTMATRICES_NOISYFB  Batch script to merge across words in noisy feedback expt.

for s=1:length(dataPaths)
    dataPath = dataPaths{s};
    file2merge = gen_fmtMatrix_attentionComp(dataPath,[],0);
    %   file2merge = 'fmtMatrix_shiftIHbeddotsshiftIHbednodotsshiftIHdeaddotsshiftIHdeadnodotsshiftIHheaddotsshiftIHheadnodotsshiftAEbeddotsshiftAEbednodotsshiftAEdeaddotsshiftAEdeadnodotsshiftAEheaddotsshiftAEheadnodots_noShiftbednoShiftdeadnoShiftheadnoShiftbednoShiftdeadnoShifthead';
    merge_fmtMatrices(dataPath,file2merge,{...
        {'shiftIHheaddots' 'shiftIHbeddots' 'shiftIHdeaddots'},...
        {'shiftIHheadnoDots' 'shiftIHbednoDots' 'shiftIHdeadnoDots'},...
        {'shiftAEheaddots' 'shiftAEbeddots' 'shiftAEdeaddots'},...
        {'shiftAEheadnoDots' 'shiftAEbednoDots' 'shiftAEdeadnoDots'}},...
        {'shiftIHdots' 'shiftIHnodots' 'shiftAEdots' 'shiftAEnodots'},0);
%    plot_fmtMatrix_attentionComp(dataPath,'fmtMatrix_shiftIHdotsshiftIHnodotsshiftAEdotsshiftAEnodots_merged','diff1'); axis([0 .3 -75 75])
end
